name: numfyx
description: "Internationalize your phone number with a few clicks"
version: 1.2.10+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2
  libphonenumber_plugin: ^0.3.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2
  excel: ^4.0.6
  path_provider: ^2.1.2
  pdf: ^3.11.1
  url_launcher: ^6.1.10
  provider: ^6.1.1
  lottie: ^3.1.0
  open_filex: 4.7.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/lottie/
